#!/usr/bin/env python3
"""
configure.py
============
Interactive first-run setup for Context Guardian. Asks a handful of
questions about YOUR specific hardware/backend and writes the answers to a
.env file, instead of making you hand-edit .env.example and guess.

Run this once after cloning:

    python configure.py

Every question has a sensible default (just press Enter to accept it) and
everything it writes can be changed later by editing .env directly, or by
re-running this script.
"""
import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
ENV_PATH = REPO_ROOT / ".env"

QUESTIONS = [
    {
        "key": "GUARDIAN_UPSTREAM_URL",
        "prompt": "OpenAI-compatible backend Guardian should forward to\n"
                   "  (your Ollama /v1 endpoint, or another proxy in front of it)",
        "default": "http://localhost:11434/v1",
    },
    {
        "key": "GUARDIAN_NUM_CTX",
        "prompt": "Context window size (in TOKENS) of the model you're actually running\n"
                   "  This is the single most important setting -- it MUST match how your\n"
                   "  backend/model is really configured, not the model's theoretical max.\n"
                   "  If you're not sure: check your inference server's running config\n"
                   "  (e.g. `ollama ps` shows the live CONTEXT value for a loaded Ollama\n"
                   "  model), or your GPU's VRAM budget if you set this yourself. Setting\n"
                   "  this too high means Guardian won't compact soon enough and your\n"
                   "  backend can still hard-error; too low means it compacts more often\n"
                   "  than it needs to.",
        "default": "32768",
    },
    {
        "key": "GUARDIAN_PORT",
        "prompt": "Port Context Guardian itself should listen on",
        "default": "8786",
    },
    {
        "key": "GUARDIAN_COMPACT_THRESHOLD",
        "prompt": "Fraction of the context window at which Guardian triggers a compaction (0.0-1.0)",
        "default": "0.85",
    },
    {
        "key": "GUARDIAN_KEEP_RECENT_MESSAGES",
        "prompt": "Number of most-recent messages to always keep verbatim (never summarized)",
        "default": "8",
    },
    {
        "key": "GUARDIAN_UPSTREAM_TIMEOUT",
        "prompt": "Seconds to wait for the upstream backend to respond\n"
                   "  (raise this if you're running a slow/local \"thinking\" model and see\n"
                   "  500 errors only on real, non-trivial requests)",
        "default": "600",
    },
    {
        "key": "GUARDIAN_LOG_PATH",
        "prompt": "Where to log compaction events (JSON lines)",
        "default": "logs/context_guardian_log.json",
    },
]


def ask(question: dict) -> str:
    default = question["default"]
    print(f"\n{question['prompt']}")
    answer = input(f"  [{default}]: ").strip()
    return answer or default


def main() -> int:
    print("Context Guardian -- first-run setup")
    print("=" * 40)
    print("Press Enter on any question to accept the default shown in [brackets].\n")

    if ENV_PATH.exists():
        overwrite = input(f".env already exists at {ENV_PATH}. Overwrite? [y/N]: ").strip().lower()
        if overwrite != "y":
            print("Left the existing .env untouched. Edit it by hand if you just wanted to tweak one value.")
            return 0

    answers = {q["key"]: ask(q) for q in QUESTIONS}

    lines = ["# Generated by configure.py -- edit freely, or re-run configure.py.\n"]
    for q in QUESTIONS:
        lines.append(f"{q['key']}={answers[q['key']]}\n")

    ENV_PATH.write_text("".join(lines), encoding="utf-8")

    print(f"\nWrote {ENV_PATH}")
    print("\nNext steps:")
    print("  1. pip install -r requirements.txt")
    print("  2. Make sure your real backend is already running.")
    print("  3. python context_guardian.py")
    print(f"  4. Point your CLI's OPENAI_BASE_URL at http://localhost:{answers['GUARDIAN_PORT']}/v1")
    print("\nSee README.md's \"Testing before you trust it\" section before pointing a real session at it.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
